---
- name: Installing and settingup KVM
  dnf:
    name: '@virtualization'
    state: latest
  become: true

- name: Start and enable libvirtd service
  service:
    name: libvirtd
    enabled: yes
    state: started
  become: true

- name: Configuring dnf
  lineinfile:
    path: /etc/libvirt/libvirtd.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^# unix_sock_group', line: 'unix_sock_group = "libvirt"' }
    - { regexp: '^# unix_sock_rw_perms', line: 'unix_sock_rw_perms = "0770"' }
  become: true

- name: Add the user to libvirt group'
  user:
    name: "{{ ansible_env.USER }}"
    groups: libvirt
    append: yes
  become: true