- name: Fedora post install 
  hosts: localhost

  tasks:
  - name: Configure dnf
    shell: sudo sed -i '8 amax_parallel_downloads=10 ' /etc/dnf/dnf.conf && sudo sed -i '9 acountme=false' /etc/dnf/dnf.conf

  - name: Check updates and install
    dnf:
      update_cache: true
      name: "*"
      state: latest
    register: fed_updated_packages

  - name: Show installed applications
    ansible.builtin.debug:
      var: fed_updated_packages.results|d()

  - name: Autoremove unneeded packages installed as dependencies
    dnf:
      autoremove: yes
    register: fed_autoremoved_packages

  - name: Show installed applications
    ansible.builtin.debug:
      var: fed_autoremoved_packages.results|d()