---
- name: Configuring dnf
  shell: sed -i '9a max_parallel_downloads=10' /etc/dnf/dnf.conf && sed -i '10a countme=false' /etc/dnf/dnf.conf
  become: true
  become_method: sudo

- name: Check updates and install
  dnf:
    update_cache: true
    name: "*"
    state: latest
  register: fed_updated_packages
  become: true
  become_method: sudo
  
- name: Show installed applications
  ansible.builtin.debug:
    var: fed_updated_packages.results|d()
