---
- name: Configuring dnf
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^max_parallel_downloads', line: 'max_parallel_downloads=10' }
    - { regexp: '^countme', line: 'countme=false' }
  become: true
  become_method: sudo

- name: Check updates and install
  dnf:
    update_cache: true
    name: "*"
    state: latest
  register: fed_updated_packages
  become: true
  become_method: sudo
  
- name: Show installed applications
  ansible.builtin.debug:
    var: fed_updated_packages.results|d()
