- name: Install some apps
  dnf:
    name: 
      - bleachbit
      - chromium
      - discord
      - firefox
      - qbittorrent
      - mpv
      - vlc
      - keepassxc
      - obs-studio
      - steam
      - uget
    state: latest
  register: fed_installed_packages
  become: true
  become_method: sudo

- name: Show installed applications
  ansible.builtin.debug:
    var: fed_installed_packages.results|d()

- name: Enable Spotify repo
  yum_repository:
    name: Spotify
    description: Spotify
    baseurl: https://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
    gpgcheck: no
    file: Spotify
  become: true
  become_method: sudo

- name: Spotify
  dnf:
   name: spotify-client
   state: latest
  become: true
  become_method: sudo

- name: VScode
  dnf:
    name: 'https://packages.microsoft.com/yumrepos/vscode/Packages/c/code-1.91.1-1720564728.el8.x86_64.rpm'
    state: present
    disable_gpg_check: yes
  become: true
  become_method: sudo

- name: Only Office
  dnf:
    name: 'https://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors.x86_64.rpm'
    state: present
    disable_gpg_check: yes
  become: true
  become_method: sudo
