- name: Install some apps
  dnf:
    name: 
      - bleachbit
      - chromium
      - discord
      - firefox
      - qbittorrent
      - mpv
      - vlc
      - keepassxc
      - obs-studio
      - steam
      - uget
    state: latest
  register: fed_installed_packages
  become: true
  become_method: sudo

- name: Show installed applications
  ansible.builtin.debug:
    var: fed_installed_packages.results|d()