---
- name: Adding Kicksecure patches
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0755'
  loop:
    - { url: 'https://raw.githubusercontent.com/Kicksecure/security-misc/master/etc/modprobe.d/30_security-misc_blacklist.conf', dest: '/etc/modprobe.d/30_security-misc_blacklist.conf' }
    - { url: 'https://raw.githubusercontent.com/Kicksecure/security-misc/master/etc/modprobe.d/30_security-misc_disable.conf', dest: '/etc/modprobe.d/30_security-misc_disable.conf' }
    - { url: 'https://raw.githubusercontent.com/Kicksecure/security-misc/master/etc/default/grub.d/40_cpu_mitigations.cfg', dest: '/etc/grub.d/40_cpu_mitigations.cfg' }
    - { url: 'https://raw.githubusercontent.com/Kicksecure/security-misc/master/etc/default/grub.d/40_distrust_cpu.cfg', dest: '/etc/grub.d/40_distrust_cpu.cfg' }
    - { url: 'https://raw.githubusercontent.com/Kicksecure/security-misc/master/etc/default/grub.d/40_enable_iommu.cfg', dest: '/etc/grub.d/40_enable_iommu.cfg' }
  become: true

- name: creating directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - /etc/systemd/system/NetworkManager.service.d
  - /etc/systemd/system/irqbalance.service.d
  become: true

- name: Divestos patches
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0755'
  loop:
    - { url: 'https://gitlab.com/divested/brace/-/raw/master/brace/usr/lib/systemd/system/NetworkManager.service.d/99-brace.conf', dest: '/etc/systemd/system/NetworkManager.service.d/99-brace.conf' }
    - { url: 'https://gitlab.com/divested/brace/-/raw/master/brace/usr/lib/systemd/system/irqbalance.service.d/99-brace.conf', dest: '/etc/systemd/system/irqbalance.service.d/99-brace.conf' }
  become: true