---
- name: Enable the RPM Fusion free repository
  dnf:
    name: 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-40.noarch.rpm'
    state: present
    disable_gpg_check: yes
  become: true
  become_method: sudo

- name: Enable the RPM Fusion non free repository
  dnf:
    name: 'https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-40.noarch.rpm'
    state: present
    disable_gpg_check: yes
  become: true
  become_method: sudo

- name: Group update
  dnf:
    name: '@core'
    state: latest
  become: true
  become_method: sudo